---
elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch

elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_plugin_dir: /usr/share/elasticsearch/plugins
elasticsearch_log_dir: /var/log/elasticsearch
elasticsearch_data_dir: /var/lib/elasticsearch
elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch
elasticsearch_pid_dir: /var/run

elasticsearch_service_startonboot: no
elasticsearch_timezone: "Etc/UTC"  # Default to UTC