---

- name: Install Oracle Java repo
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    creates=/usr/lib/jvm/java-8-oracle

- name: Install Oracle Java
  apt: name=oracle-java8-installer state=present update_cache=yes

- name: Installing ES GPG key
  shell: wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -

- name: Adding elasticsearch repository
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present

- name: Install ElasticSearch
  apt: name=elasticsearch state=present update_cache=yes

- name: Configuring ElasticSearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644
  notify: Restart Elasticsearch

- name: Configure /etc/default/elasticsearch
  template:
    src=elasticsearch.default.j2
    dest=/etc/default/elasticsearch
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    mode=0644
  notify: Restart Elasticsearch