---
- hosts: tag_Group_web
  sudo: yes

  vars:
    www_dir: "/var/www"

  roles:
    - { role: hatchup.web }
    - { role: geerlingguy.nginx  }
    - { role: nbz4live.php-fpm  }


- hosts: tag_Group_es
  sudo: yes

  vars:
    elasticsearch_network_host: 0.0.0.0
    elasticsearch_heap_size: 256m
    elasticsearch_max_open_files: 65535
    elasticsearch_max_locked_memory: unlimited
    elasticsearch_timezone: "Europe/Amsterdam"
    elasticsearch_cluster_name: elasticsearch-hatchup
    elasticsearch_misc_auto_create_index: "true"
    elasticsearch_java_opts: "-Djava.net.preferIPv4Stack=true"

  roles:
    - { role: hatchup.es }