---
- hosts: tag_Group_web
  sudo: yes

  roles:
    - { role: hatchup.web }
    - { role: geerlingguy.nginx  }
    - { role: nbz4live.php-fpm  }


- hosts: tag_Group_es
  sudo: yes

  vars:
    elasticsearch_heap_size: 1g
    elasticsearch_max_open_files: 65535
    elasticsearch_max_locked_memory: unlimited
    elasticsearch_timezone: "Europe/Amsterdam"
    elasticsearch_cluster_name: elasticsearch-hatchup
    elasticsearch_node_max_local_storage_nodes: 1
    elasticsearch_index_mapper_dynamic: "true"
    elasticsearch_memory_bootstrap_mlockall: "true"
    elasticsearch_gateway_type: local
    elasticsearch_gateway_recover_after_nodes: 1
    elasticsearch_gateway_recover_after_time: 2m
    elasticsearch_gateway_expected_nodes: 1
    elasticsearch_discovery_zen_minimum_master_nodes: 1
    elasticsearch_discovery_zen_ping_timeout: 30s
    elasticsearch_discovery_zen_ping_multicast_enabled: "true"
    elasticsearch_misc_auto_create_index: "true"
    elasticsearch_misc_query_bool_max_clause_count: 4096
    elasticsearch_misc_disable_delete_all_indices: "true"
    elasticsearch_java_opts: "-XX:-UseSuperWord"

  roles:
    - { role: gpstathis.elasticsearch }